# GET  http://localhost:4000/api/url/google.com

# GET  http://localhost:4000/api/url/myphonebook11.herokuapp.com


GET  http://localhost:4000/api/url



# Content-Type: application/json

# {
#     "url": "https://google.com",
#     "url_details": [
#         {
#             "time_stamp": "thu aug 26 2021 12:49:00",
#             "status_code": 200
#         }
#     ]
# }


// to save data in database.